"""
Django settings for flight_blender project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import secrets
from pathlib import Path

import dj_database_url
from dotenv import find_dotenv, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ENV_FILE = find_dotenv()
if ENV_FILE:
    load_dotenv(ENV_FILE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

def env_bool(key: str, default: bool = False) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    value = str(raw).strip().lower()
    if value in {"1", "true", "t", "yes", "y", "on"}:
        return True
    if value in {"0", "false", "f", "no", "n", "off", ""}:
        return False
    return default

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("IS_DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
DJANGO_SECRET_KEY = (os.getenv("DJANGO_SECRET_KEY") or "").strip()
LEGACY_SECRET_KEY = (os.getenv("SECRET_KEY") or "").strip()
if DJANGO_SECRET_KEY:
    SECRET_KEY = DJANGO_SECRET_KEY
elif LEGACY_SECRET_KEY:
    SECRET_KEY = LEGACY_SECRET_KEY
else:
    if DEBUG:
        SECRET_KEY = secrets.token_urlsafe(64)
    else:
        raise RuntimeError("DJANGO_SECRET_KEY (or legacy SECRET_KEY) must be set when IS_DEBUG=0")

BYPASS_AUTH_TOKEN_VERIFICATION = env_bool("BYPASS_AUTH_TOKEN_VERIFICATION", False)
if BYPASS_AUTH_TOKEN_VERIFICATION and not DEBUG:
    raise RuntimeError("BYPASS_AUTH_TOKEN_VERIFICATION must not be enabled when IS_DEBUG=0")

if not DEBUG and SECRET_KEY in {"DJANGO_SECRET", "change-me-django-secret-key", "change-me-secret-key"}:
    raise RuntimeError("DJANGO_SECRET_KEY is using a placeholder value; set DJANGO_SECRET_KEY to a secure random string")

# Optional: key used for JOSE/JWKS signing (separate from Django's SECRET_KEY).
OIDC_SIGNING_PRIVATE_KEY_PEM = (os.getenv("OIDC_SIGNING_PRIVATE_KEY_PEM") or "").strip()
OIDC_SIGNING_PUBLIC_JWKS = {"keys": []}
if OIDC_SIGNING_PRIVATE_KEY_PEM:
    try:
        from jwcrypto import jwk  # imported only when signing is configured

        _oidc_key = jwk.JWK.from_pem(OIDC_SIGNING_PRIVATE_KEY_PEM.encode("utf-8"))
        public_data = {"alg": "RS256", "use": "sig", "kid": _oidc_key.thumbprint()}
        public_data.update(_oidc_key.export_public(as_dict=True))
        OIDC_SIGNING_PUBLIC_JWKS = {"keys": [public_data]}
    except Exception as error:  # noqa: BLE001
        raise RuntimeError("OIDC_SIGNING_PRIVATE_KEY_PEM must be a valid RSA private key PEM") from error

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "openutm.net").split(",")

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "rest_framework",
    "flight_declaration_operations",
    "detect_and_avoid_operations",
    "constraint_operations",
    "geo_fence_operations",
    "scd_operations",
    "uss_operations",
    "flight_feed_operations",
    "surveillance_monitoring_operations",
    "conformance_monitoring_operations",
    "notification_operations",
    "rid_operations",
    "weather_monitoring_operations",
    "utm_adapter",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "flight_blender.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "homebase", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "flight_blender.asgi.application"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {}
USE_LOCAL_SQLITE_DATABASE = int(os.getenv("USE_LOCAL_SQLITE_DATABASE", "0"))
if USE_LOCAL_SQLITE_DATABASE:
    DATABASES = {
        "default": {
            "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
            "NAME": os.getenv("DB_DATABASE", os.path.join(BASE_DIR, "flight_blender.sqlite3")),
        }
    }
else:
    db_config = dj_database_url.config(conn_max_age=600)
    if not db_config:
        db_config = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "flight_blender.sqlite3"),
        }
    DATABASES["default"] = db_config

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

ASTM_F3623_SDSP_CUSTOM_DATA_FUSER_CLASS = os.getenv(
    "ASTM_F3623_SDSP_CUSTOM_DATA_FUSER_CLASS",
    "surveillance_monitoring_operations.utils.TrafficDataFuser",
)
CUSTOM_VOLUME_4D_GENERATION_CLASS = os.getenv("CUSTOM_VOLUME_4D_GENERATION_CLASS", "")

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
if DEBUG:
    BROKER_URL = os.getenv("REDIS_BROKER_URL", "redis://localhost:6379/")
else:
    BROKER_URL = os.getenv("REDIS_BROKER_URL", "redis://redis:6379/")


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [BROKER_URL],
        },
    },
}


CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_BROKER_URL = BROKER_URL
CELERY_RESULT_BACKEND = BROKER_URL
CELERY_TIMEZONE = "UTC"
# DataFlair #Logging Information
LOGGING = {
    "version": 1,
    # Version of logging
    "disable_existing_loggers": False,
    # disable logging
    # Handlers #############################################################
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    # Loggers ####################################################################
    "loggers": {
        "django": {
            "handlers": ["console"],
            "propagate": True,
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
    },
}


# Weather service
WEATHER_API_BASE_URL = "https://api.open-meteo.com/v1/forecast"
